---
common:
  skipper:
    copy:
      - source: inventory.json
        target: something_else/foobar.json

  # upon inspection of the compiled templates you will quickly notice that you will have to overwrite this value in the target
  subscription_id: "INVALID DEFAULT VALUE" 
  foo:
    bar: "test"
  baz: ${common:foo:bar}
  baz2: ${foo:bar}
  from_target: "${alphaNum}_CHANGED"
