---
target:
  skipper:
    use: 
      - azure
      - targets.dev.common
    templates:
      class_aliases:
        - class: targets.dev.common # all classes with that name prefix are going to be affected
          alias: terraform
  azure:
    common:
      subscription_id: "45e4fca6-f05b-4354-951a-3ea194d2da85" # random uuid

  # Refactoring terraform identifiers has never been easier. 
  # Just change one variable from the imported class and you're done :)
  terraform:
    identifiers:
      resource_group: "changed_identifier"
